version: "3.9"
services:
  backend:
    build:
      context: ./backend/server
    ports:
      - "5000:5000"
    volumes:
      - ./backend/server:/app
    environment:
      - NODE_ENV=development

  frontend:
    build:
      context: ./frontend
    ports:
      - "19000:19000"
    volumes:
      - ./frontend:/app
    environment:
      - NODE_ENV=development
    stdin_open: true
    tty: true
