version: '3.8'
services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules  # Add this line to preserve node_modules
    env_file:  # This ensures the .env file is passed to the container
      - ./backend/.env
    depends_on:
      - db
    environment:
      - NODE_ENV=development

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    stdin_open: true
    env_file:
      - ./frontend/.env

  db:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./backend/data:/data/db  # Retain or remove based on your persistence needs

volumes:
  db_data:  # Retain if persistence is required
